### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-audlexdec-vp-vm#1]
instructions zou ik dit van maken:

    'const PRE_PRACTICE_INSTRUCTION =
    "<strong>Dear participant,</strong><BR><BR>"        +
    "Thank you for participating in this experiment."   +
    "<BR><BR>"                                          +
    "You are now going to see and hear words, one "     +
    "after the other. The words come in pairs, first "  +
    "a written word, then a spoken word. Pay attention to "          + 
    "both the written word <i>and</i> the word you "         +
    "<i>hear</i>.<BR><BR>"           +

    "Your task is to indicate as "                      +
    "quickly as possible whether you think "            +
    "<i>both words are existing words or not</i>. "         +
    "Try to make no mistakes.<BR><BR>"                  +

    "After clicking OK, please put your "               +
    "<i>index</i> fingers on the <kbd>%correct_key%</kbd> key "                  + 
    "and the <kbd>%incorrect_key%</kbd> key. Try to keep them "     +
    "there during the <i>entire experiment</i>!<BR>"+

    "<ul>"                                              + 
    "<li>Hit the <kbd>%correct_key%</kbd> key for "     + 
    "<strong>Yes</strong>. "                            + 
    "<sub><i>(Use this 'Yes' key to proceed throughout "+ 
    "the experiment)</i>.</sub></li>"                   +
    "<li>Hit the <kbd>%incorrect_key%</kbd> key for "   +
    "<strong>No</strong>.</li>"                         + 
    "</ul>"                                             +

    "First, you can practice.<BR><BR>"                  +
    "<i>Click OK to start practicing.</i>"
    ;`

**Comment by irisopgithub** [comment]
ter info nog: ik geloof niet dat het supergebruikelijk is om te vragen om beide woorden te beoordelen, maar het komt wel voor, ik ben het wel tegengekomen in de literatuur. omdat het iets minder gebruikelijk is en studenten er misschien niet op komen om het zo te doen, wil ik het juist wel graag zo in de template hebben. het stond ook zo in de zep-templates, en in de EDDA-cursus heeft de helft van de groepjes het zo gelaten (met als motivatie dat je de pp dan dwingt om ook het eerste woord serieus te processen), en de helft heeft het aangepast naar 'alleen het tweede woord beoordelen'.

**Comment by jcvanelst** [comment]
ik kan niet twee keer dezelfde truc gebruiken zoals in je voorstel:

"After clicking OK, please put your "               +
"<i>index</i> fingers on the <kbd>%correct_key%</kbd> key "                  + 
"and the <kbd>%incorrect_key%</kbd> key. Try to keep them "     +
"there during the <i>entire experiment</i>!<BR>"+

In één instructie kan dat kennelijk maar één keer.

**Comment by jcvanelst** [comment]
effects is anders dat er de tweede keer (in de unordered list) anders de literals komen te staan zoals hierboven. dit was ook de reden om dat overal zo te doen.

**Comment by irisopgithub** [comment]
ok, how about this:

    ` const PRE_PRACTICE_INSTRUCTION =
    "<strong>Dear participant,</strong><BR><BR>"        +
    "Thank you for participating in this experiment."   +
    "<BR><BR>"                                          +
    "You are now going to see and hear words, one "     +
    "after the other. The words come in pairs, first "  +
    "a written word, then a spoken word. Pay attention to "          + 
    "both the written word <i>and</i> the word you "         +
    "<i>hear</i>.<BR><BR>"           +

    "Your task is to indicate as "                      +
    "quickly as possible whether you think "            +
    "<i>both words are existing words or not</i>. "         +
    "Try to make no mistakes.<BR><BR>"                  +

    "After clicking OK, please put your dominant"               +
    "<i>index</i> finger on the <kbd>%correct_key%</kbd> key"                  + 
    "to respond <strong>Yes</strong>, and to proceed to the next part" +
    "throughout the experiment." +
    "Put your other index finger on the <kbd>%incorrect_key%</kbd> key to respond <strong>No</strong>." +
    "Try to keep your fingers on those keys "     +
    "during the <i>entire experiment</i>!<BR><BR>"+

    "First, you can practice.<BR><BR>"                  +
    "<i>Click OK to start practicing.</i>"
    ;`

**Comment by irisopgithub** [comment]
ik heb 'm nog geupdatetetetet, gepruts met die strings en die plusjes, maar zo moet-ie goed zijn geloof ik.

**Comment by jcvanelst** [comment]
yes. gedaan hoor, ook netjes uitgelijnd qua code.
ik vind de layout zelf minder dan met een lijst, maar het maakt me natuurlijk ook 
<img width="1223" alt="Screen Shot 2020-12-18 at 13 33 24" src="https://user-images.githubusercontent.com/4124202/102615376-1a498f80-4136-11eb-8185-e9a79a09b816.png">
niet uit...
(vs)
<img width="1260" alt="Screen Shot 2020-12-18 at 13 31 18" src="https://user-images.githubusercontent.com/4124202/102615291-f25a2c00-4135-11eb-8df2-be16ab2008a8.png">

**Comment by irisopgithub** [comment]
ja, jouw voorstel is veel beter! mooi zo met die lijst. alleen nog een spatie tussen auditory en Your. en ik wil wel graag houden, 'first a written word, then a spoken word'. (visual en auditory zal niet voor alle ppn duidelijk zijn).

**Comment by jcvanelst** [comment]
okay
