### ISSUE TITLE
ja-knop werkt niet om door te gaan

### ISSUE THREAD

**Issue by irisopgithub** [UiL-OTS-labs/jspsych-audlexdec-vp-vm#2]
heb het alleen in deze template getest

**Comment by irisopgithub** [comment]
ik denk dat hier de verkeerde pagina in staat tussen practice en testblok. want daar staat ook nog 'If you have any questions at this moment, please ask yourself now.', en dat was in de hoofd-template iets beters geworden.

**Comment by jcvanelst** [comment]
de ja knop werkt nu weer. De 'iets beters' weet ik niet. heb ik kennelijk niet gedaan, staat overal nog zo.
